export const FesArray = [
  {
    ID: "FES",
    id: "3-MARR-DES-MER-MARR",
    name: "3 Days Tour from Fes to Merzouga Desert",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-11.jpg",
    url: "/tours-and-circuits/tours-from-fes/3-days-from-fes-to-merzouga",
    price: "200",
    descount: "20",
    days: " 3  ",
    nights: "2",
    from: "Fes",
    popular: true,
    desc: "3 Days Morocco Tour From Marrakech to Merzouga gives you a magnificent oportunity to enjoy the very best of Morocco's top attractions,",
  },
  {
    ID: "FES",
    id: "3-days-from-fes-via-merzouga-to-marrakech",
    name: "3 Days Tour from Fes via Merzouga to Marrakech",
    image: "/../../../images/altas-images/altas-images-10.jpg",
    url: "/tours-and-circuits/tours-from-fes/3-days-from-fes-via-merzouga-to-marrakech",
    price: "200",
    descount: "20",
    days: " 3  ",
    nights: "2",
    from: "Fes",
    popular: true,
    desc: "The 3 Days Tour from Marrakech Via Merzouga to Fes gives you the chance to experience southern Morocco's beauty, like the magnificent high Atlas Mountains,",
  },
  ,
  {
    ID: "FES",
    id: "4-days-from-fes-to-merzouga",
    name: "4 Days Tour from Fes to Merzouga Desert",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-16.jpg",
    url: "/tours-and-circuits/tours-from-fes/4-days-from-fes-to-merzouga",
    price: "200",
    descount: "20",
    days: " 4  ",
    nights: "3",
    from: "Fes",
    popular: true,
    desc: "The 4 Days Round Tour from Marrakech Via Merzouga Sahara Desert is among the most extensive Marrakech Desert Tours that come with us. It is the best option available for people",
  },

  {
    ID: "FES",
    id: "4-days-from-fes-via-merzouga-to-marrakech",
    name: "4 Days Tour from Fes to Marrakech via Merzouga Desert.",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-19.jpg",
    url: "/tours-and-circuits/tours-from-fes/4-days-from-fes-via-merzouga-to-marrakech",
    price: "200",
    descount: "20",
    days: " 4  ",
    nights: "3",
    from: "Fes",
    popular: true,
    desc: "The 4 Day Merzouga Desert Trip Marrakech to Fes. is among the most extensive Marrakech Desert Tours that come with us. It is the best option available for people who have",
  },
  {
    ID: "FES",
    id: "5-days-from-fes-to-merzouga",
    name: "5 Days Tour from Fes to Merzouga Desert.",
    image: "/../../../images/fes-images/fes-images4.jpg",
    url: "/tours-and-circuits/tours-from-fes/5-days-from-fes-to-merzouga",
    price: "250",
    descount: "30",
    days: " 5  ",
    nights: "4",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "5-days-from-from-via-merzouga-to-marrakech",
    name: "5 Day Merzouga Desert Trip Fes to Marrakech.",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-23.jpg",
    url: "/tours-and-circuits/tours-from-fes/5-days-from-from-via-merzouga-to-marrakech",
    price: "250",
    descount: "30",
    days: " 5  ",
    nights: "4",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "6-MARR-DES-MER-MARR",
    name: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/6-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: " 6  ",
    nights: "4",
    from: "Fes",
    popular: true,
    desc: "",
  },
  {
    ID: "FES",
    id: "6-MARR-DES-MER-FES",
    name: "6 Days Tour From Marrakech Via  Sahara Desert to Fes",
    image: "/../../../images/fes-images/fes-images3.webp",
    url: "/tours-and-circuits/tours-from-fes/6-days-from-marrakech-via-merzouga-to-fes",
    price: "250",
    descount: "30",
    days: " 6  ",
    nights: "5",
    from: "Fes",
    popular: false,
    desc: "6 Days Tour from Marrakech Via Merzouga Desert to Fes is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the Long",
  },
  {
    ID: "FES",
    id: "7-MARR-DES-MER-MARR",
    name: "7 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/7-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: " 7  ",
    nights: "6",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "7-MARR-DES-MER-MARR",
    name: "7 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/7-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: " 7  ",
    nights: "6",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "3-MARR-DES-MER-MARR",
    name: "8 Days From Marrakech Merzouga Desert ",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-3.jpg",
    url: "/tours-and-circuits/tours-from-fes/8-days-from-marrakech-to-merzouga",
    price: "200",
    descount: "20",
    days: " 8  ",
    nights: "7",
    from: "Fes",
    popular: true,
    desc: "3 Days Morocco Tour From Marrakech to Merzouga gives you a magnificent oportunity to enjoy the very best of Morocco's top attractions,",
  },
  {
    ID: "FES",
    id: "3-MARR-DES-MER-FES",
    name: "8 Days Tour from Marrakech Via Merzouga to Fes",
    image: "/../../../images/merzouga-images/desert-images/desert-images1.jpg",
    url: "/tours-and-circuits/tours-from-fes/8-days-from-marrakech-via-merzougato-fes",
    price: "200",
    descount: "20",
    days: " 8  ",
    nights: "7",
    from: "Fes",
    popular: true,
    desc: "The 3 Days Tour from Marrakech Via Merzouga to Fes gives you the chance to experience southern Morocco's beauty, like the magnificent high Atlas Mountains,",
  },
  ,
  {
    ID: "FES",
    id: "4-MARR-DES-MER-MARR",
    name: "9 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/camp-mages/camp-images-3.jpg",
    url: "/tours-and-circuits/tours-from-fes/9-days-from-marrakech-to-merzouga",
    price: "200",
    descount: "20",
    days: " 9  ",
    nights: "8",
    from: "Fes",
    popular: true,
    desc: "The 4 Days Round Tour from Marrakech Via Merzouga Sahara Desert is among the most extensive Marrakech Desert Tours that come with us. It is the best option available for people",
  },

  {
    ID: "FES",
    id: "9-MARR-DES-MER-FES",
    name: "9 Day Merzouga Desert Trip Marrakech to Fes.",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-7.jpg",
    url: "/tours-and-circuits/tours-from-fes/9-days-from-marrakech-via-merzouga-to-fes",
    price: "200",
    descount: "20",
    days: " 9  ",
    nights: "8",
    from: "Fes",
    popular: true,
    desc: "The 4 Day Merzouga Desert Trip Marrakech to Fes. is among the most extensive Marrakech Desert Tours that come with us. It is the best option available for people who have",
  },
  {
    ID: "FES",
    id: "10-MARR-DES-MER-MARR",
    name: "10 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-10.jpg",
    url: "/tours-and-circuits/tours-from-fes/10-days-from-marrakech-to-merzouga",
    price: "250",
    descount: "30",
    days: " 10",
    nights: "9",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "10-MARR-DES-MER-FES",
    name: "10 Days Tour from Marrakech Via Merzouga Desert to Fes",
    image: "/../../../images/merzouga-images/desert-images/desert-images7.jpg",
    url: "/tours-and-circuits/tours-from-fes/10-days-from-marrakech-via-merzouga-to-fes",
    price: "250",
    descount: "30",
    days: "10",
    nights: "9",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "11-MARR-DES-MER-MARR",
    name: "11 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-10.jpg",
    url: "/tours-and-circuits/tours-from-fes/10-days-from-marrakech-to-merzouga",
    price: "250",
    descount: "30",
    days: "11",
    nights: "10",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "11-MARR-DES-MER-FES",
    name: "11 Days Tour from Marrakech Via Merzouga Desert to Fes",
    image: "/../../../images/merzouga-images/desert-images/desert-images7.jpg",
    url: "/tours-and-circuits/tours-from-fes/10-days-from-marrakech-via-merzouga-to-fes",
    price: "250",
    descount: "30",
    days: "11",
    nights: "10",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "12-MARR-DES-MER-MARR",
    name: "12 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/12-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "12",
    nights: "11",
    from: "Fes",
    popular: true,
    desc: "",
  },
  {
    ID: "FES",
    id: "12-MARR-DES-MER-FES",
    name: "12 Days Tour From Marrakech Via  Sahara Desert to Fes",
    image: "/../../../images/fes-images/fes-images3.webp",
    url: "/tours-and-circuits/tours-from-fes/12-days-from-marrakech-via-merzouga-to-fes",
    price: "250",
    descount: "30",
    days: "12",
    nights: "11",
    from: "Fes",
    popular: false,
    desc: "6 Days Tour from Marrakech Via Merzouga Desert to Fes is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the Long",
  },
  {
    ID: "FES",
    id: "13-MARR-DES-MER-MARR",
    name: "13 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/13-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "13",
    nights: "12",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "13-MARR-DES-MER-MARR",
    name: "13 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/13-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "13",
    nights: "12",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "14-MARR-DES-MER-MARR",
    name: "14 Days From Marrakech Merzouga Desert ",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-3.jpg",
    url: "/tours-and-circuits/tours-from-fes/14-days-from-marrakech-to-merzouga",
    price: "200",
    descount: "20",
    days: "14",
    nights: "13",
    from: "Fes",
    popular: true,
    desc: "3 Days Morocco Tour From Marrakech to Merzouga gives you a magnificent oportunity to enjoy the very best of Morocco's top attractions,",
  },
  {
    ID: "FES",
    id: "14-MARR-DES-MER-FES",
    name: "14 Days Tour from Marrakech Via Merzouga to Fes",
    image: "/../../../images/merzouga-images/desert-images/desert-images1.jpg",
    url: "/tours-and-circuits/tours-from-fes/14-days-from-marrakech-via-merzougato-fes",
    price: "200",
    descount: "20",
    days: "14",
    nights: "13",
    from: "Fes",
    popular: true,
    desc: "The 3 Days Tour from Marrakech Via Merzouga to Fes gives you the chance to experience southern Morocco's beauty, like the magnificent high Atlas Mountains,",
  },
  ,
  {
    ID: "FES",
    id: "15-MARR-DES-MER-MARR",
    name: "15 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/camp-mages/camp-images-3.jpg",
    url: "/tours-and-circuits/tours-from-fes/15-days-from-marrakech-to-merzouga",
    price: "200",
    descount: "20",
    days: "15",
    nights: "14",
    from: "Fes",
    popular: true,
    desc: "The 4 Days Round Tour from Marrakech Via Merzouga Sahara Desert is among the most extensive Marrakech Desert Tours that come with us. It is the best option available for people",
  },

  {
    ID: "FES",
    id: "15-MARR-DES-MER-FES",
    name: "15 Day Merzouga Desert Trip Marrakech to Fes.",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-7.jpg",
    url: "/tours-and-circuits/tours-from-fes/15-days-from-marrakech-via-merzouga-to-fes",
    price: "200",
    descount: "20",
    days: "15",
    nights: "14",
    from: "Fes",
    popular: true,
    desc: "The 4 Day Merzouga Desert Trip Marrakech to Fes. is among the most extensive Marrakech Desert Tours that come with us. It is the best option available for people who have",
  },
  {
    ID: "FES",
    id: "16-MARR-DES-MER-MARR",
    name: "16 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image:
      "/../../../images/merzouga-images/camels-images/desert-camels-merzouga-10.jpg",
    url: "/tours-and-circuits/tours-from-fes/16-days-from-marrakech-to-merzouga",
    price: "250",
    descount: "30",
    days: "16",
    nights: "15",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "16-MARR-DES-MER-FES",
    name: "16 Days Tour from Marrakech Via Merzouga Desert to Fes",
    image: "/../../../images/merzouga-images/desert-images/desert-images7.jpg",
    url: "/tours-and-circuits/tours-from-fes/16-days-from-marrakech-via-merzouga-to-fes",
    price: "250",
    descount: "30",
    days: "16",
    nights: "15",
    from: "Fes",
    popular: true,
    desc: "5 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "17-MARR-DES-MER-MARR",
    name: "17 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/17-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "17",
    nights: "16",
    from: "Fes",
    popular: true,
    desc: "",
  },
  {
    ID: "FES",
    id: "17-MARR-DES-MER-FES",
    name: "17 Days Tour From Marrakech Via  Sahara Desert to Fes",
    image: "/../../../images/fes-images/fes-images3.webp",
    url: "/tours-and-circuits/tours-from-fes/17-days-from-marrakech-via-merzouga-to-fes",
    price: "250",
    descount: "30",
    days: "17",
    nights: "16",
    from: "Fes",
    popular: false,
    desc: "6 Days Tour from Marrakech Via Merzouga Desert to Fes is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the Long",
  },
  {
    ID: "FES",
    id: "18-MARR-DES-MER-MARR",
    name: "18 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/18-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "18",
    nights: "17",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "18-MARR-DES-MER-MARR",
    name: "18 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/18-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "18",
    nights: "17",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "19-MARR-DES-MER-MARR",
    name: "19 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/19-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "19",
    nights: "18",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "19-MARR-DES-MER-MARR",
    name: "19 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/19-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "19",
    nights: "18",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "20-MARR-DES-MER-MARR",
    name: "20 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/20-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "20",
    nights: "19",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "20-MARR-DES-MER-MARR",
    name: "20 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "20",
    nights: "19",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "21-MARR-DES-MER-MARR",
    name: "21 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/21-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "21",
    nights: "20",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "21-MARR-DES-MER-MARR",
    name: "21 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/21-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "21",
    nights: "20",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "22-MARR-DES-MER-MARR",
    name: "22 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/22-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "22",
    nights: "21",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "22-MARR-DES-MER-MARR",
    name: "22 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/22-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "22",
    nights: "21",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "23-MARR-DES-MER-MARR",
    name: "23 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/23-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "23",
    nights: "22",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "23-MARR-DES-MER-MARR",
    name: "23 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/23-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "23",
    nights: "22",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "24-MARR-DES-MER-MARR",
    name: "24 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/24-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "24",
    nights: "23",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "24-MARR-DES-MER-MARR",
    name: "24 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/24-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "24",
    nights: "23",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "25-MARR-DES-MER-MARR",
    name: "25 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/25-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "25",
    nights: "24",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "25-MARR-DES-MER-MARR",
    name: "25 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/25-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "25",
    nights: "24",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "26-MARR-DES-MER-MARR",
    name: "26 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/26-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "26",
    nights: "25",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "26-MARR-DES-MER-MARR",
    name: "26 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/26-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "26",
    nights: "25",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "27-MARR-DES-MER-MARR",
    name: "27 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/27-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "27",
    nights: "26",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "27-MARR-DES-MER-MARR",
    name: "27 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/27-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "27",
    nights: "26",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "28-MARR-DES-MER-MARR",
    name: "28 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/28-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "28",
    nights: "27",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "28-MARR-DES-MER-MARR",
    name: "28 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/28-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "28",
    nights: "27",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "29-MARR-DES-MER-MARR",
    name: "29 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/29-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "29",
    nights: "28",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "29-MARR-DES-MER-MARR",
    name: "29 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/29-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "29",
    nights: "28",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "30-MARR-DES-MER-MARR",
    name: "30 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/30-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "30",
    nights: "29",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "30-MARR-DES-MER-MARR",
    name: "30 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/30-days-from-marrakech-via-merzouga-to-fes",
    price: "280",
    descount: "35",
    days: "30",
    nights: "29",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "31-MARR-DES-MER-MARR",
    name: "31 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/31-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "31",
    nights: "30",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "32-MARR-DES-MER-MARR",
    name: "32 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/32-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "32",
    nights: "31",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "33-MARR-DES-MER-MARR",
    name: "33 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/33-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "33",
    nights: "32",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "34-MARR-DES-MER-MARR",
    name: "34 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/34-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "34",
    nights: "33",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "35-MARR-DES-MER-MARR",
    name: "35 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/35-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "35",
    nights: "34",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "36-MARR-DES-MER-MARR",
    name: "36 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/36-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "36",
    nights: "35",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "37-MARR-DES-MER-MARR",
    name: "37 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/37-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "37",
    nights: "36",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "38-MARR-DES-MER-MARR",
    name: "38 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/38-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "38",
    nights: "37",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "39-MARR-DES-MER-MARR",
    name: "39 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/39-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "39",
    nights: "38",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  {
    ID: "FES",
    id: "40-MARR-DES-MER-MARR",
    name: "40 Days Round Tour from Marrakech Via Merzouga Sahara Desert",
    image: "/../../../images/merzouga-images/desert-images/desert-images10.jpg",
    url: "/tours-and-circuits/tours-from-fes/40-days-from-marrakech-to-merzouga",
    price: "280",
    descount: "35",
    days: "40",
    nights: "39",
    from: "Fes",
    popular: false,
    desc: "6 Days Round Tour from Marrakech Via Merzouga Sahara Desert is one of the major Marrakech desert tours which we offer and the best option for travelers who have plenty of time to spend in Morocco and would like to break the",
  },
  //--------------------------------Marrakech end --------------------------------//
  //----------------------------------------------------------------------------//

  //----------------------------------------------------------------------------//
  //--------------------------------Fes begin--------------------------------//
  //--------------------------------Fes begin--------------------------------//
  //--------------------------------Fes begin--------------------------------//
  //----------------------------------------------------------------------------//
];
